config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'
  resources :relationships, only: [:create, :destroy]
  resources :favorites,only: [:create,:destroy,:index]
  resources :posts do
    resources :comments
  end

  resources :conversations,only: [:index,:create] do
    resources :messages,only: [:index,:new,:create,:destroy]
  end
 end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
    }

  # 必ずdevise_forより下に記載しないとエラー発生
  resources :users,only: [:index,:show] do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation, optional: true
  belongs_to :user, optional: true
  validates_presence_of :body, :conversation_id, :user_id
  validates :body, presence: true, length: { maximum: 75 }

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = Message.where(id: @messages[-10..-1].pluck(:id))
    end

    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end

    if @messages.last
      @messages.where.not(user_id: current_user.id).update_all(read: true)
    end

    @messages = @messages.order(:created_at)
    @message = @conversation.messages.build
  end

  def create
    @messages = @conversation.messages.order(:created_at)
    @message = @conversation.messages.build(message_params)
    @message.user_id = current_user.id
    respond_to do |format|
      if @message.save
        format.js { render :index }
      else
        format.html { redirect_to conversation_messages_path, notice: t('messages.cannot') }
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    respond_to do |format|
      if @message.destroy
        format.html {}
        format.js { render :destroy }
      else
        format.html {redirect_to conversation_messages_path(@conversation)}
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: [@conversation,@message]) do |form| %>
  <div class="message-form">
    <div class="field">
      <p><%= form.text_area :body,class:"message_text" %></p>
    </div>
    <div class="actions">
      <p><%= form.submit class:"btn btn-orange",id:"post_message" %></p>
        <%= link_to t('users.index'), users_path,class:"btn btn-green" %>
    </div>
  </div>
<% end %>

app/views/messages/_index.html.erb
<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body.present? %>
      <div class="balloon_container">
        <% if current_user.id == message.user.id %>
          <div class="balloon4" id="mycomment<%=message.id %>">
        <% else %>
          <div class="balloon3">
        <% end %>
        <div class="content">
          <div class="header">
            <strong><%= message.user.name %></strong><%= message.message_time %>
          </div>
          <div class="list">
            <div>
              <%= link_to image_tag(message.user.icon.url,class:"icon"),user_path(message.user.id) %>
            </div>
            <span id="message<%= @message.id %>"><%= message.body %></span>
            <% if message.user == current_user %>
              <%= message.read ? t('messages.read') : t('messages.unread') %>
              <%= link_to t('common.destroy'), conversation_message_path(message.conversation.id,message.id),remote: true,method: :delete,id:"message_destroy" %>
            <% end %>
          </div>
        </div>
      </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/messages/destroy.js.erb
$('#mycomment<%=@message.id %>').remove();

app/views/messages/index.html.erb
<% if @over_ten %>
  <%= link_to t('messages.last'), '?m=all' %>
<% end %>
<!-- 全てのメッセージを表示させるパーシャル -->
<div id="message_area">
  <%= render partial: 'messages/index', locals: { messages: @messages, conversation: @converation } %>
</div>
<!-- メッセージの入力欄を作るためのパーシャル -->
 <%= render partial: 'messages/form', locals: { message: @message, conversation: @converation } %>

app/views/messages/index.js.erb
$("#message_area").html("<%= j(render 'messages/index', { messages: @messages ,conversation: @conversation }) %>")
$("textarea").val('')