config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'
  resources :relationships, only: [:create, :destroy]
  resources :favorites,only: [:create,:destroy,:index]
  resources :posts do
    resources :comments
  end

  resources :conversations,only: [:index,:create] do
    resources :messages,only: [:index,:new,:create,:destroy]
  end
 end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
    }

  # 必ずdevise_forより下に記載しないとエラー発生
  resources :users,only: [:index,:show] do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :icon, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :messages, dependent: :destroy
  has_many :sender_conversations, foreign_key: 'sender_id', class_name: 'Conversation', dependent: :destroy
  has_many :recipient_conversations, foreign_key: 'recipient_id', class_name: 'Conversation', dependent: :destroy
  validates :name, presence: true,length: {maximum: 35}
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :introduction,length: {maximum: 150}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook,:google_oauth2,:twitter]
          # omniauth_providers: %i[facebook twitter google]


    def follow!(other_user)
      active_relationships.create!(followed_id: other_user.id)
    end

    def following?(other_user)
      active_relationships.find_by(followed_id: other_user.id)
    end

    def unfollow!(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
    end

# ゲストユーザーのログインのメソッド
    def self.guest
      find_or_create_by!(name: 'guest',email: 'guest@example.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      end
    end

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   # assuming the user model has a name
        user.icon = auth.info.icon # assuming the user model has an image
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        # user.skip_confirmation!
      end
    end

    private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end

    # def last_admin_not_delete
    #   throw(:abort) if User.where(admin: true).length == 1 && self.admin?
    # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def facebook
    callback_for(:facebook)
  end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: provider.capitalize
      sign_in_and_redirect @user, event: :authentication
      session[:user_id] = @user.id #add
    else
      session['devise.#{provider}_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
   # redirect_to root_path
  end
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create


  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to root_path, alert:  t('users.guest_authentication')
   end
 end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def check_guest
    if resource.email == 'guest@example.com'
       redirect_to root_path, alert:  t('users.guest_authentication')
    end
  end

#
  # def build_resource(hash={})
  #   hash[:uid] = User.create_unique_string
  #   super
  # end



  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  #
  #The path used after edit profile.
  def after_update_path_for(resource)
    user_path(current_user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # ログインした後の遷移先
   def after_sign_up_path_for(resource)
     edit_user_registration_url(current_user.id)
   end

   protected

   def update_resource(resource, params)
     resource.update_without_password(params)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


  def new_guest
    user = User.guest
    sign_in user
    redirect_to users_path, notice: t('users.guest_login')
    rescue ActiveRecord::RecordInvalid => e
    pp e.record&.errors
    redirect_to root_path, alert: t('users.guest_error')
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,:following, :followers]
  before_action :authenticate_user!

  def index
    if params[:search]
      @results = User.ransack(params[:q]).result.page(params[:page]).per(8)
    else
      @results = User.all.order(id: "DESC").page(params[:page]).per(8)
    end

    @languages = Language.all
    @labels = Label.all
  end

  def show
    @users = @user.posts
  end

  def following
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :icon, :age, :gender, :country, :native_language,
      :learning_language,:introduction, label_ids: [] )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit t('users.following_user'),class:"btn btn-blue" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit t('users.cancel'),class:"btn btn-blue" %>
    <% end %>
  <% end %>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>"><%= t('users.following') %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
  </a>
  <a href="<%= followers_user_path(@user) %>"><%= t('users.followers') %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </a>
</div>

app/views/users/index.html.erb
<h1><%= t('users.index') %></h1>
<%= search_form_for @search do |f| %>
  <div class="search_form">
    <div class="label_form">
      <%= f.select :labels_id_eq, @labels.collect {|label| [label.hobby,label.id]} , {include_blank: t('users.hobby_search')}, {class: 'form-control select_hobby',id:"hobby"} %>
    </div>
    <div class="form-inline serch_box">
      <%= f.select :native_language_eq,@languages.collect {|nl| [nl.name]} , {include_blank: t('users.native_search')}, {class: 'form-control select_language',id:"native"} %>
      <%= f.select :learning_language_eq,@languages.collect {|nl| [nl.name]} , {include_blank: t('users.learning_search')}, {class: 'form-control select_language',id:"learning"} %>
    </div>
  </div>
  <div class="actions search_button">
    <%= f.submit t('users.search'),name:'search',class:"btn btn-blue" %>
    <p><%= link_to t('users.index'), users_path,class:"btn btn-green" %></p>
  </div>
<% end %>
<div class="flex-container">
  <% @results.each do |result| %>
    <% if result.id != current_user.id %>
      <div class="profile-card">
        <div class="profile-card__inner">
          <div class="profile-thumb">
            <p><%=link_to image_tag(result.icon.url),user_path(result.id)%></p>
          </div>
          <div class="profile-content">
            <span class="profile-name"><%= link_to result.name,user_path(result.id) %></span>
          </div>
          <p><%= t('users.native') %>:<%= result.native_language %></p>
          <p><%= t('users.learning') %>:<%= result.learning_language %></p>
          <p><%= t('users.hobby') %>:
            <%result.labels.each do |label| %>
              <%= label.hobby %>
            <% end %>
          </p>
          <div class="user-buttons">
            <%= render 'follow_form', user: result %>
            <%= link_to t('users.message'), conversations_path(sender_id: current_user.id, recipient_id: result.id),class:"btn btn-green", method: :post %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="page"><%= paginate @results %></div>

app/views/users/show.html.erb
<h2><%= t('users.profile') %></h2>
<div class="pr-container">
  <div class="pr-icon">
    <p><%= image_tag(@user.icon.url,class:"proicon") %></p>
  </div>
  <div class="pr-text">
    <p><%= render 'stats' %></p>
    <p><%= t('users.name') %>: <%= @user.name %></p>
    <p><%= t('users.age') %> <%= @user.age %></p>
    <p><%= t('users.gender') %> : <%= @user.gender %></p>
    <p><%= t('users.country') %>: <%= @user.country %></p>
    <p><%= t('users.native') %>: <%= @user.native_language %></p>
    <p><%= t('users.learning') %> : <%= @user.learning_language %></p>
    <p><%= t('users.hobby') %>: <%@user.labels.each do |label| %>
      <%= label.hobby %>
    <% end %></p>
    <p><%= t('users.introduction') %>: <br> <%= @user.introduction %></p>
  </div>
  <% if current_user == @user %>
    <p><%= link_to t('users.edit_profile'), edit_user_registration_url,id:"edit_button",class:"btn btn-pink" %></p>
  <% end %>
  <p><%= link_to t('users.back_user'), users_path,class:"btn btn-green" %></p>
</div>
<% @users.each do |user| %>
  <div class="flex-container">
    <div class="post-card">
      <div class="post-card-inner">
        <div class="post-thumb">
          <% if user.image.url %>
            <p><%=link_to image_tag(user.image.url),post_path(user.id)%></p>
          <% end %>
        </div>
        <div class="post-content">
          <p><%= user.title %></p>
          <p><%= user.content %></p>
          <div class="detail-button">
            <span><%= link_to t('common.detail'), post_path(user.id),class:"btn btn-orange" %></span>
          </div>
          <div class="user-show-post-buttons">
            <% if @user == current_user %>
              <span>
                <%= link_to t('common.edit'), edit_post_path(user.id), data: { confirm: t('common.edit?') },class:"btn btn-pink" %>
              </span>
              <span>
                <%= link_to t('common.destroy'), post_path(user.id), method: :delete, data: { confirm: t('common.delete') },class:"btn btn-red" %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show_follow.html.erb
<h1><%= t('users.followed_index') %></h1>
<div class="flex-container">
  <% @user.following.each do |user| %>
    <div class="follow-card">
      <div class="profile-card__inner">
        <div class="profile-thumb">
          <p><%=link_to image_tag(user.icon.url),user_path(user.id)%></p>
        </div>
        <div class="profile-content">
          <span class="profile-name"><%= link_to user.name,user_path(user.id) %></span>
          <div class="message_button">
            <%= link_to t('users.message'), conversations_path(sender_id: current_user.id, recipient_id: user.id),class:"btn btn-green", method: :post %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show_follower.html.erb
<h1><%= t('users.follower_index') %></h1>
<div class="flex-container">
  <% @user.followers.each do |user| %>
    <div class="follow-card">
      <div class="profile-card__inner">
        <div class="profile-thumb">
          <p><%=link_to image_tag(user.icon.url),user_path(user.id)%></p>
        </div>
        <div class="profile-content">
          <span class="profile-name"><%= link_to user.name,user_path(user.id) %></span>
          <div class="message_button">
            <%= link_to t('users.message'), conversations_path(sender_id: current_user.id, recipient_id: user.id),class:"btn btn-green", method: :post %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>