config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'
  resources :relationships, only: [:create, :destroy]
  resources :favorites,only: [:create,:destroy,:index]
  resources :posts do
    resources :comments
  end

  resources :conversations,only: [:index,:create] do
    resources :messages,only: [:index,:new,:create,:destroy]
  end
 end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
    }

  # 必ずdevise_forより下に記載しないとエラー発生
  resources :users,only: [:index,:show] do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PictureUploader
  has_many :favorites, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :user
  has_many  :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: {maximum: 75}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:edit,:update,:destroy]
  before_action :check_user, only:[:edit,:update,:destroy]

  def index
    @posts = Post.all.order(created_at: "DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: t('posts.finished')
    else
      render :new
    end
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id )
    @favorite_count = Favorite.where(post_id: @post.id).count
    @comments = @post.comments
    @comment = @post.comments.build
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: t('posts.edited')
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: t('posts.deleted')
  end

  def check_user
    if @post.user.id != current_user.id
      redirect_to posts_path, notice: t('posts.not_authenticate')
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content,:image, :image_cache)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %><%= t('common.have_errors') %></h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group2">
    <div class="post_image">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <div class="blog_title">
      <%= f.label :title %>
      <%= f.text_field :title,class:"form-control title",placeholder:t('posts.type_title') %>
    </div>
    <div class="post_content">
      <%= f.label :content %>
      <%= f.text_field :content,class:"form-control content",placeholder:t('posts.type_content') %>
    </div>
    <div class="post-form-buttons">
      <%= f.submit class:" btn btn-green" %>
      <%= link_to t('posts.back_post'), posts_path,class:"btn btn-orange back-index" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2 class="post_head"><%= t('posts.edit_post') %></h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="post-index-top">
  <h1><%= t('posts.index') %></h1>
  <%= link_to t('posts.new_post'), new_post_path,class:"btn btn-green",id:"create_post" %>
</div>
<% @posts.each do |post| %>
  <div class="flex-container">
    <div class="post-card">
      <div class="post-card-inner">
        <div class="post-thumb">
          <% if post.image.url %>
            <p><%=link_to image_tag(post.image.url,class:"index-img"),post_path(post.id)%></p>
          <% end %>
        </div>
        <div class="post-content">
          <%= link_to image_tag(post.user.icon.url,class:"post-icon"),user_path(post.user.id) %>
          <%= link_to post.user.name,user_path(post.user.id) %>
        </div>
        <p><%= post.title %></p>
        <p><%= post.content %></p>
      </div>
      <div class="post-index-detail">
        <%= link_to t('common.detail'), post_path(post.id),class:"btn btn-orange" %>
      </div>
      <div class="post-button">
        <% if post.user.id == current_user.id %>
          <span><%= link_to t('common.edit'), edit_post_path(post.id), data: { confirm: t('common.edit?') },class:"btn btn-pink" %></span>
          <span><%= link_to t('common.destroy'), post_path(post.id), method: :delete, data: { confirm: t('common.delete?') },class:"btn btn-red" %></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2><%= t('posts.new_post') %></h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= t('posts.show') %></h1>
<div class="flex-container">
  <div class="post-card">
    <div class="post-card-inner">
      <div class="post-thumb">
        <% if @post.image.url %>
          <p><%= image_tag @post.image.url %></p>
        <% end %>
      </div>
      <p><%= @post.title %></p>
      <p><%= @post.content %></p>
      <div class="favo-text">
        <%= render partial: 'favorites/favorite' %>
      </div>
    </div>
    <div class="post-button">
      <% if @post.user.id == current_user.id %>
        <span><%= link_to t('common.edit'), edit_post_path(@post.id), data: { confirm: t('common.edit?') },class:"btn btn-pink",id:"edit_post" %></span>
        <span><%= link_to t('common.destroy'), post_path(@post.id), method: :delete, data: { confirm: t('common.delete?') },class:"btn btn-red",id:"delete_post" %></span>
      <% end %>
    </div>
  </div>
</div>
<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, post: @post } %>
</div>
<%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
<p class="post-back"><%= link_to t('posts.back_post'), posts_path,class:"btn btn-orange" %></p>