config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'
  resources :relationships, only: [:create, :destroy]
  resources :favorites,only: [:create,:destroy,:index]
  resources :posts do
    resources :comments
  end

  resources :conversations,only: [:index,:create] do
    resources :messages,only: [:index,:new,:create,:destroy]
  end
 end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
    }

  # 必ずdevise_forより下に記載しないとエラー発生
  resources :users,only: [:index,:show] do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true, length: { maximum: 75 }
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User', optional: true
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User', optional: true
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)",
    sender_id,recipient_id, recipient_id, sender_id)
  end

  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :users, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :label, optional: true
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation, optional: true
  belongs_to :user, optional: true
  validates_presence_of :body, :conversation_id, :user_id
  validates :body, presence: true, length: { maximum: 75 }

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, PictureUploader
  has_many :favorites, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :user
  has_many  :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: {maximum: 75}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :icon, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :messages, dependent: :destroy
  has_many :sender_conversations, foreign_key: 'sender_id', class_name: 'Conversation', dependent: :destroy
  has_many :recipient_conversations, foreign_key: 'recipient_id', class_name: 'Conversation', dependent: :destroy
  validates :name, presence: true,length: {maximum: 35}
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :introduction,length: {maximum: 150}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook,:google_oauth2,:twitter]
          # omniauth_providers: %i[facebook twitter google]


    def follow!(other_user)
      active_relationships.create!(followed_id: other_user.id)
    end

    def following?(other_user)
      active_relationships.find_by(followed_id: other_user.id)
    end

    def unfollow!(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
    end

# ゲストユーザーのログインのメソッド
    def self.guest
      find_or_create_by!(name: 'guest',email: 'guest@example.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      end
    end

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   # assuming the user model has a name
        user.icon = auth.info.icon # assuming the user model has an image
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        # user.skip_confirmation!
      end
    end

    private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end

    # def last_admin_not_delete
    #   throw(:abort) if User.where(admin: true).length == 1 && self.admin?
    # end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-warning">
  <%= link_to "Polybility", root_path,class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item nav-link ">
          <%= link_to t('nav.user'), users_path,class:"white" %>
        </li>
        <li class="nav-item nav-link">
           <%= link_to t('nav.post'), posts_path,class:"white" %>
        </li>
        <li class="nav-item nav-link ">
          <%= link_to t('nav.favorite'), favorites_path,class:"white" %>
        </li>
        <li class="nav-item nav-link ">
          <%= link_to t('nav.chat'), conversations_path,class:"white" %>
        </li>
        <li class="nav-item nav-link ">
          <%= link_to t('nav.following'), following_user_path(current_user),class:"white" %>
        </li>
        <li class="nav-item nav-link ">
          <%= link_to t('nav.follower'), followers_user_path(current_user),class:"white" %>
        </li>
      <% else %>
        <li class="nav-item nav-link ">
          <%= link_to t('nav.signup'), new_user_registration_path,class:"white" %>
        </li>
        <li class="nav-item nav-link ">
          <%= link_to t('nav.login'), new_user_session_path,class:"white" %>
        </li>
      <% end %>
      <% if I18n.locale.to_s == "en" %>
        <li class="nav-item nav-link">
           <%= link_to('日本語', :locale => 'ja') %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to('简体中文', :locale => 'zh') %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to('繁体中文', :locale => 'zc') %>
        </li>
      <% elsif I18n.locale.to_s == "zh" %>
        <li class="nav-item nav-link">
          <%= link_to('日本語', :locale => 'ja') %>
        </li>
        <li class="nav-item nav-link">
           <%= link_to('English', :locale => 'en') %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to('繁体中文', :locale => 'zc') %>
        </li>
        <% elsif I18n.locale.to_s == "zc" %>
          <li class="nav-item nav-link">
            <%= link_to('日本語', :locale => 'ja') %>
          </li>
          <li class="nav-item nav-link">
             <%= link_to('English', :locale => 'en') %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to('简体中文', :locale => 'zh') %>
          </li>
      <% else %>
        <li class="nav-item nav-link">
           <%= link_to('English', :locale => 'en') %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to('简体中文', :locale => 'zh') %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to('繁体中文', :locale => 'zc') %>
        </li>
      <% end %>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
        <% if current_user.try(:admin?) %>
          <li class="nav-item nav-link white">
            <%= link_to t('nav.admin'),rails_admin_path %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item nav-link nav-right ">
             <%=link_to image_tag(current_user.icon.url,class:"nav-icon"),user_path(current_user.id) %>
          </li>
          <li class="nav-item nav-link ">
            <%= link_to current_user.name + t('nav.mr_ms'), user_path(current_user.id),class:"white" %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to t('nav.logout'), destroy_user_session_path, method: :delete,class:"white" %>
          </li>
        <% else %>
          <li class="nav-item nav-link navbar-right ">
            <%= link_to t('nav.guest_login') ,users_guest_sign_in_path, method: :post,class:"white" %>
          </li>
        <% end %>
      </ul>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polybility</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body id="wrapper">

    <%= render "layouts/navbar" %>
    <%= render "components/notice" %>
    <%= yield %>
    <%= render "components/footer" %>

  <!-- 背景のjs -->
    <script src="https://cdn.jsdelivr.net/npm/bubbly-bg@1.0.0/dist/bubbly-bg.js"></script>
    <script>
      bubbly({
        colorStart: "#fff4e6",
        colorStop: "#ffe9e4",
        blur: 2,
        bubbles: 40,
        compose: "source-over",
        bubbleFunc:() => `hsla(${Math.random() * 50}, 100%, 50%, .3)`
      });
    </script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>